# Redirect HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name event.test international-events2026.esaunggul.ac.id;
    return 301 https://$host$request_uri;
}

# HTTPS server
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_tokens off;
    client_max_body_size 128M;
    client_body_buffer_size 128M;

    server_name event.test international-events2026.esaunggul.ac.id;
    root /var/www/html/public;

    index index.php index.html;

    ssl_certificate     /etc/nginx/ssl/event.test.crt;
    ssl_certificate_key /etc/nginx/ssl/event.test.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # CORS headers for all responses
    add_header Access-Control-Allow-Origin  "*" always;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-CSRF-TOKEN, X-Requested-With" always;

    # Handle preflight OPTIONS request
    location / {
        if ($request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin  "*";
            add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS";
            add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-CSRF-TOKEN, X-Requested-With";
            add_header Content-Length 0;
            add_header Content-Type  text/plain;
            return 204;
        }

        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_HOST $http_host;
        fastcgi_param HTTPS on;
    }

    location ~ /\.ht {
        deny all;
    }
}
